# Generated by Django 4.2.4 on 2023-09-01 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email_name',
            new_name='email',
        ),
    ]
