# Generated by Django 4.2.4 on 2023-09-02 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_email_name_order_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
